"""estrutura inicial ExameX

Revision ID: 536151abe3ea
Revises: 
Create Date: 2025-11-23 12:01:09.870610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '536151abe3ea'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Administrador',
    sa.Column('idAdministrador', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('senha', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idAdministrador')
    )
    op.create_index(op.f('ix_Administrador_idAdministrador'), 'Administrador', ['idAdministrador'], unique=False)
    op.create_table('Curso',
    sa.Column('idCurso', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('idCurso')
    )
    op.create_index(op.f('ix_Curso_idCurso'), 'Curso', ['idCurso'], unique=False)
    op.create_table('Dificuldade',
    sa.Column('idDificuldade', sa.Integer(), nullable=False),
    sa.Column('nota', sa.Float(), nullable=True),
    sa.Column('dificuldade', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idDificuldade')
    )
    op.create_index(op.f('ix_Dificuldade_idDificuldade'), 'Dificuldade', ['idDificuldade'], unique=False)
    op.create_table('Materia',
    sa.Column('idMateria', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.PrimaryKeyConstraint('idMateria')
    )
    op.create_index(op.f('ix_Materia_idMateria'), 'Materia', ['idMateria'], unique=False)
    op.create_table('Professor',
    sa.Column('idProfessor', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=45), nullable=True),
    sa.Column('senha', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('idProfessor')
    )
    op.create_index(op.f('ix_Professor_idProfessor'), 'Professor', ['idProfessor'], unique=False)
    op.create_table('ProfessorMateria',
    sa.Column('idProfessor', sa.Integer(), nullable=False),
    sa.Column('idMateria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMateria'], ['Materia.idMateria'], ),
    sa.ForeignKeyConstraint(['idProfessor'], ['Professor.idProfessor'], ),
    sa.PrimaryKeyConstraint('idProfessor', 'idMateria')
    )
    op.create_table('QuestaoDissertativa',
    sa.Column('idQuestaoDissertativa', sa.Integer(), nullable=False),
    sa.Column('idDificuldade', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.Column('idProfessor', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idDificuldade'], ['Dificuldade.idDificuldade'], ),
    sa.ForeignKeyConstraint(['idProfessor'], ['Professor.idProfessor'], ),
    sa.PrimaryKeyConstraint('idQuestaoDissertativa')
    )
    op.create_index(op.f('ix_QuestaoDissertativa_idQuestaoDissertativa'), 'QuestaoDissertativa', ['idQuestaoDissertativa'], unique=False)
    op.create_table('QuestaoObjetiva',
    sa.Column('idQuestaoObjetiva', sa.Integer(), nullable=False),
    sa.Column('idDificuldade', sa.Integer(), nullable=True),
    sa.Column('idProfessor', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=500), nullable=True),
    sa.Column('imagem', mysql.LONGBLOB(), nullable=True),
    sa.ForeignKeyConstraint(['idDificuldade'], ['Dificuldade.idDificuldade'], ),
    sa.ForeignKeyConstraint(['idProfessor'], ['Professor.idProfessor'], ),
    sa.PrimaryKeyConstraint('idQuestaoObjetiva')
    )
    op.create_index(op.f('ix_QuestaoObjetiva_idQuestaoObjetiva'), 'QuestaoObjetiva', ['idQuestaoObjetiva'], unique=False)
    op.create_table('Turma',
    sa.Column('idTurma', sa.Integer(), nullable=False),
    sa.Column('idCurso', sa.Integer(), nullable=True),
    sa.Column('turma', sa.String(length=45), nullable=True),
    sa.Column('periodo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['Curso.idCurso'], ),
    sa.PrimaryKeyConstraint('idTurma')
    )
    op.create_index(op.f('ix_Turma_idTurma'), 'Turma', ['idTurma'], unique=False)
    op.create_table('Alternativa',
    sa.Column('idAlternativa', sa.Integer(), nullable=False),
    sa.Column('idQuestaoObjetiva', sa.Integer(), nullable=True),
    sa.Column('texto', sa.String(length=200), nullable=True),
    sa.Column('imagem', sa.LargeBinary(), nullable=True),
    sa.Column('afirmativa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idQuestaoObjetiva'], ['QuestaoObjetiva.idQuestaoObjetiva'], ),
    sa.PrimaryKeyConstraint('idAlternativa')
    )
    op.create_index(op.f('ix_Alternativa_idAlternativa'), 'Alternativa', ['idAlternativa'], unique=False)
    op.create_table('Prova',
    sa.Column('idProva', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=100), nullable=True),
    sa.Column('descricao', sa.String(length=255), nullable=True),
    sa.Column('observacoes', sa.String(length=500), nullable=True),
    sa.Column('pdf', mysql.LONGBLOB(), nullable=True),
    sa.Column('qrCode', mysql.LONGBLOB(), nullable=True),
    sa.Column('idProfessor', sa.Integer(), nullable=True),
    sa.Column('idTurma', sa.Integer(), nullable=True),
    sa.Column('idMateria', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idMateria'], ['Materia.idMateria'], ),
    sa.ForeignKeyConstraint(['idProfessor'], ['Professor.idProfessor'], ),
    sa.ForeignKeyConstraint(['idTurma'], ['Turma.idTurma'], ),
    sa.PrimaryKeyConstraint('idProva')
    )
    op.create_index(op.f('ix_Prova_idProva'), 'Prova', ['idProva'], unique=False)
    op.create_table('TurmaMateria',
    sa.Column('idTurma', sa.Integer(), nullable=False),
    sa.Column('idMateria', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idMateria'], ['Materia.idMateria'], ),
    sa.ForeignKeyConstraint(['idTurma'], ['Turma.idTurma'], ),
    sa.PrimaryKeyConstraint('idTurma', 'idMateria')
    )
    op.create_table('Dashboard',
    sa.Column('idDashboard', sa.Integer(), nullable=False),
    sa.Column('idProva', sa.Integer(), nullable=True),
    sa.Column('media', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['idProva'], ['Prova.idProva'], ),
    sa.PrimaryKeyConstraint('idDashboard')
    )
    op.create_index(op.f('ix_Dashboard_idDashboard'), 'Dashboard', ['idDashboard'], unique=False)
    op.create_table('ProvaQuestaoDissertativa',
    sa.Column('idProva', sa.Integer(), nullable=False),
    sa.Column('idQuestaoDissertativa', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProva'], ['Prova.idProva'], ),
    sa.ForeignKeyConstraint(['idQuestaoDissertativa'], ['QuestaoDissertativa.idQuestaoDissertativa'], ),
    sa.PrimaryKeyConstraint('idProva', 'idQuestaoDissertativa')
    )
    op.create_table('ProvaQuestaoObjetiva',
    sa.Column('idProva', sa.Integer(), nullable=False),
    sa.Column('idQuestaoObjetiva', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['idProva'], ['Prova.idProva'], ),
    sa.ForeignKeyConstraint(['idQuestaoObjetiva'], ['QuestaoObjetiva.idQuestaoObjetiva'], ),
    sa.PrimaryKeyConstraint('idProva', 'idQuestaoObjetiva')
    )
    op.drop_index(op.f('ix_QuestaoObjetiva_idQuestaoObjetiva'), table_name='questaoobjetiva')
    op.drop_table('questaoobjetiva')
    op.drop_index(op.f('ix_QuestaoDissertativa_idQuestaoDissertativa'), table_name='questaodissertativa')
    op.drop_table('questaodissertativa')
    op.drop_index(op.f('ix_Materia_idMateria'), table_name='materia')
    op.drop_table('materia')
    op.drop_index(op.f('ix_Professor_idProfessor'), table_name='professor')
    op.drop_table('professor')
    op.drop_index(op.f('ix_Curso_idCurso'), table_name='curso')
    op.drop_table('curso')
    op.drop_table('provaquestaodissertativa')
    op.drop_table('professormateria')
    op.drop_table('turmamateria')
    op.drop_index(op.f('ix_Dashboard_idDashboard'), table_name='dashboard')
    op.drop_table('dashboard')
    op.drop_table('provaquestaoobjetiva')
    op.drop_index(op.f('ix_Dificuldade_idDificuldade'), table_name='dificuldade')
    op.drop_table('dificuldade')
    op.drop_index(op.f('ix_Turma_idTurma'), table_name='turma')
    op.drop_table('turma')
    op.drop_index(op.f('ix_Alternativa_idAlternativa'), table_name='alternativa')
    op.drop_table('alternativa')
    op.drop_index(op.f('ix_Prova_idProva'), table_name='prova')
    op.drop_table('prova')
    op.drop_index(op.f('ix_Administrador_idAdministrador'), table_name='administrador')
    op.drop_table('administrador')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrador',
    sa.Column('idAdministrador', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('senha', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.PrimaryKeyConstraint('idAdministrador'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Administrador_idAdministrador'), 'administrador', ['idAdministrador'], unique=False)
    op.create_table('prova',
    sa.Column('idProva', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('observacoes', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('pdf', sa.BLOB(), nullable=True),
    sa.Column('qrCode', sa.BLOB(), nullable=True),
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idTurma', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('idMateria', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=150), nullable=False),
    sa.Column('descricao', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255), nullable=True),
    sa.ForeignKeyConstraint(['idMateria'], ['materia.idMateria'], name='prova_ibfk_3'),
    sa.ForeignKeyConstraint(['idProfessor'], ['professor.idProfessor'], name='prova_ibfk_1'),
    sa.ForeignKeyConstraint(['idTurma'], ['turma.idTurma'], name='prova_ibfk_2'),
    sa.PrimaryKeyConstraint('idProva'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Prova_idProva'), 'prova', ['idProva'], unique=False)
    op.create_table('alternativa',
    sa.Column('idAlternativa', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idQuestaoObjetiva', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('texto', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=True),
    sa.Column('imagem', sa.BLOB(), nullable=True),
    sa.Column('afirmativa', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idQuestaoObjetiva'], ['questaoobjetiva.idQuestaoObjetiva'], name=op.f('alternativa_ibfk_1')),
    sa.PrimaryKeyConstraint('idAlternativa'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Alternativa_idAlternativa'), 'alternativa', ['idAlternativa'], unique=False)
    op.create_table('turma',
    sa.Column('idTurma', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idCurso', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turma', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('periodo', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idCurso'], ['curso.idCurso'], name='turma_ibfk_1'),
    sa.PrimaryKeyConstraint('idTurma'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Turma_idTurma'), 'turma', ['idTurma'], unique=False)
    op.create_table('dificuldade',
    sa.Column('idDificuldade', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nota', mysql.FLOAT(), nullable=True),
    sa.Column('dificuldade', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.PrimaryKeyConstraint('idDificuldade'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Dificuldade_idDificuldade'), 'dificuldade', ['idDificuldade'], unique=False)
    op.create_table('provaquestaoobjetiva',
    sa.Column('idProva', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idQuestaoObjetiva', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idProva'], ['prova.idProva'], name=op.f('provaquestaoobjetiva_ibfk_1')),
    sa.ForeignKeyConstraint(['idQuestaoObjetiva'], ['questaoobjetiva.idQuestaoObjetiva'], name=op.f('provaquestaoobjetiva_ibfk_2')),
    sa.PrimaryKeyConstraint('idProva', 'idQuestaoObjetiva'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('dashboard',
    sa.Column('idDashboard', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idProva', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['idProva'], ['prova.idProva'], name=op.f('dashboard_ibfk_1')),
    sa.PrimaryKeyConstraint('idDashboard'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Dashboard_idDashboard'), 'dashboard', ['idDashboard'], unique=False)
    op.create_table('turmamateria',
    sa.Column('idTurma', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idMateria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idMateria'], ['materia.idMateria'], name=op.f('turmamateria_ibfk_2')),
    sa.ForeignKeyConstraint(['idTurma'], ['turma.idTurma'], name=op.f('turmamateria_ibfk_1')),
    sa.PrimaryKeyConstraint('idTurma', 'idMateria'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('professormateria',
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idMateria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idMateria'], ['materia.idMateria'], name=op.f('professormateria_ibfk_2')),
    sa.ForeignKeyConstraint(['idProfessor'], ['professor.idProfessor'], name=op.f('professormateria_ibfk_1')),
    sa.PrimaryKeyConstraint('idProfessor', 'idMateria'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('provaquestaodissertativa',
    sa.Column('idProva', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('idQuestaoDissertativa', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['idProva'], ['prova.idProva'], name=op.f('provaquestaodissertativa_ibfk_1')),
    sa.ForeignKeyConstraint(['idQuestaoDissertativa'], ['questaodissertativa.idQuestaoDissertativa'], name=op.f('provaquestaodissertativa_ibfk_2')),
    sa.PrimaryKeyConstraint('idProva', 'idQuestaoDissertativa'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('curso',
    sa.Column('idCurso', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=25), nullable=False),
    sa.PrimaryKeyConstraint('idCurso'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Curso_idCurso'), 'curso', ['idCurso'], unique=False)
    op.create_table('professor',
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('email', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.Column('senha', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=True),
    sa.PrimaryKeyConstraint('idProfessor'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Professor_idProfessor'), 'professor', ['idProfessor'], unique=False)
    op.create_table('materia',
    sa.Column('idMateria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=45), nullable=False),
    sa.PrimaryKeyConstraint('idMateria'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_Materia_idMateria'), 'materia', ['idMateria'], unique=False)
    op.create_table('questaodissertativa',
    sa.Column('idQuestaoDissertativa', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idDificuldade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('imagem', sa.BLOB(), nullable=True),
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idDificuldade'], ['dificuldade.idDificuldade'], name=op.f('questaodissertativa_ibfk_1')),
    sa.ForeignKeyConstraint(['idProfessor'], ['professor.idProfessor'], name=op.f('questaodissertativa_ibfk_2')),
    sa.PrimaryKeyConstraint('idQuestaoDissertativa'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_QuestaoDissertativa_idQuestaoDissertativa'), 'questaodissertativa', ['idQuestaoDissertativa'], unique=False)
    op.create_table('questaoobjetiva',
    sa.Column('idQuestaoObjetiva', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('idDificuldade', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('titulo', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=500), nullable=True),
    sa.Column('imagem', mysql.LONGBLOB(), nullable=True),
    sa.Column('idProfessor', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['idDificuldade'], ['dificuldade.idDificuldade'], name=op.f('questaoobjetiva_ibfk_1')),
    sa.ForeignKeyConstraint(['idProfessor'], ['professor.idProfessor'], name=op.f('questaoobjetiva_ibfk_2')),
    sa.PrimaryKeyConstraint('idQuestaoObjetiva'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_QuestaoObjetiva_idQuestaoObjetiva'), 'questaoobjetiva', ['idQuestaoObjetiva'], unique=False)
    op.drop_table('ProvaQuestaoObjetiva')
    op.drop_table('ProvaQuestaoDissertativa')
    op.drop_index(op.f('ix_Dashboard_idDashboard'), table_name='Dashboard')
    op.drop_table('Dashboard')
    op.drop_table('TurmaMateria')
    op.drop_index(op.f('ix_Prova_idProva'), table_name='Prova')
    op.drop_table('Prova')
    op.drop_index(op.f('ix_Alternativa_idAlternativa'), table_name='Alternativa')
    op.drop_table('Alternativa')
    op.drop_index(op.f('ix_Turma_idTurma'), table_name='Turma')
    op.drop_table('Turma')
    op.drop_index(op.f('ix_QuestaoObjetiva_idQuestaoObjetiva'), table_name='QuestaoObjetiva')
    op.drop_table('QuestaoObjetiva')
    op.drop_index(op.f('ix_QuestaoDissertativa_idQuestaoDissertativa'), table_name='QuestaoDissertativa')
    op.drop_table('QuestaoDissertativa')
    op.drop_table('ProfessorMateria')
    op.drop_index(op.f('ix_Professor_idProfessor'), table_name='Professor')
    op.drop_table('Professor')
    op.drop_index(op.f('ix_Materia_idMateria'), table_name='Materia')
    op.drop_table('Materia')
    op.drop_index(op.f('ix_Dificuldade_idDificuldade'), table_name='Dificuldade')
    op.drop_table('Dificuldade')
    op.drop_index(op.f('ix_Curso_idCurso'), table_name='Curso')
    op.drop_table('Curso')
    op.drop_index(op.f('ix_Administrador_idAdministrador'), table_name='Administrador')
    op.drop_table('Administrador')
    # ### end Alembic commands ###
